# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1190, 803)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.loginFrame = QtWidgets.QFrame(self.centralwidget)
        self.loginFrame.setStyleSheet("#loginFrame{\n"
"background-color:#EFEFEF;\n"
"}\n"
"QLabel\n"
"{\n"
"color:white;\n"
"font-style:Century Gothic;\n"
"font-size:38px;\n"
"margin-left:40px;\n"
"}")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.loginFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sideBar = QtWidgets.QFrame(self.loginFrame)
        self.sideBar.setMinimumSize(QtCore.QSize(400, 750))
        self.sideBar.setMaximumSize(QtCore.QSize(410, 16777215))
        self.sideBar.setStyleSheet("#sideBar{\n"
"background-color: #48ACAC;\n"
"}")
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.label = QtWidgets.QLabel(self.sideBar)
        self.label.setGeometry(QtCore.QRect(40, 50, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("#QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label.setObjectName("label")
        self.logo = QtWidgets.QLabel(self.sideBar)
        self.logo.setGeometry(QtCore.QRect(-20, 0, 131, 101))
        self.logo.setStyleSheet("#logo\n"
"{\n"
"margin:-50px;\n"
"}")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/Images/image-removebg-preview (2).png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label_2 = QtWidgets.QLabel(self.sideBar)
        self.label_2.setGeometry(QtCore.QRect(140, 270, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.sideBar)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("#QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.sideBar)
        self.label_4.setGeometry(QtCore.QRect(230, 370, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("#QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.sideBar)
        self.frame_2 = QtWidgets.QFrame(self.loginFrame)
        self.frame_2.setMinimumSize(QtCore.QSize(500, 500))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(100, 120, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(108, 108, 108);")
        self.label_5.setObjectName("label_5")
        self.txtUserName = QtWidgets.QLineEdit(self.frame_2)
        self.txtUserName.setGeometry(QtCore.QRect(150, 310, 351, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtUserName.setFont(font)
        self.txtUserName.setStyleSheet("background-color:white;\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:black;\n"
"padding-bottom:7px;")
        self.txtUserName.setPlaceholderText("")
        self.txtUserName.setObjectName("txtUserName")
        self.btnLogIn = QtWidgets.QPushButton(self.frame_2)
        self.btnLogIn.setGeometry(QtCore.QRect(240, 540, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogIn.setFont(font)
        self.btnLogIn.setStyleSheet("\n"
"#btnLogIn {\n"
"    background-color: #48ACAC;\n"
"    border-radius:50px;\n"
"    color:white\n"
"}\n"
"#btnLogIn:hover{\n"
"background-color: #2F958D;\n"
"}")
        self.btnLogIn.setObjectName("btnLogIn")
        self.txtPassword = QtWidgets.QLineEdit(self.frame_2)
        self.txtPassword.setGeometry(QtCore.QRect(150, 390, 351, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("background-color:white;\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setPlaceholderText("")
        self.txtPassword.setObjectName("txtPassword")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(150, 280, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(108, 108, 108);\n"
"font: 10pt \"Century Gothic\";\n"
"margin-left:0px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(150, 360, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(108, 108, 108);\n"
"font: 10pt \"Century Gothic\";\n"
"margin-left:0px;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(150, 450, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(108, 108, 108);\n"
"font: 10pt \"Century Gothic\";\n"
"margin-left:0px;")
        self.label_8.setObjectName("label_8")
        self.cmbRole = QtWidgets.QComboBox(self.frame_2)
        self.cmbRole.setGeometry(QtCore.QRect(280, 450, 211, 22))
        self.cmbRole.setObjectName("cmbRole")
        self.cmbRole.addItem("")
        self.cmbRole.addItem("")
        self.cmbRole.addItem("")
        self.cmbRole.addItem("")
        self.cmbRole.addItem("")
        self.btnClose = QtWidgets.QPushButton(self.frame_2)
        self.btnClose.setGeometry(QtCore.QRect(720, 10, 41, 41))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setAutoFillBackground(False)
        self.btnClose.setStyleSheet("\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btnClose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/icons8-close-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        self.btnClose.setIconSize(QtCore.QSize(48, 48))
        self.btnClose.setAutoDefault(False)
        self.btnClose.setDefault(False)
        self.btnClose.setFlat(True)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.loginFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "APTO Distribution"))
        self.label_2.setText(_translate("MainWindow", "Welcome To "))
        self.label_3.setText(_translate("MainWindow", "APTO Distribution "))
        self.label_4.setText(_translate("MainWindow", "System"))
        self.label_5.setText(_translate("MainWindow", "Login To Continue"))
        self.btnLogIn.setText(_translate("MainWindow", "L o g  I n"))
        self.label_6.setText(_translate("MainWindow", "User Name or Email"))
        self.label_7.setText(_translate("MainWindow", "Password"))
        self.label_8.setText(_translate("MainWindow", "Select Role :"))
        self.cmbRole.setItemText(0, _translate("MainWindow", "Admin"))
        self.cmbRole.setItemText(1, _translate("MainWindow", "Manager"))
        self.cmbRole.setItemText(2, _translate("MainWindow", "Sales Agent"))
        self.cmbRole.setItemText(3, _translate("MainWindow", "Order Dispatcher"))
        self.cmbRole.setItemText(4, _translate("MainWindow", "Delivery Man"))
import UI_Classes.resources2_rc
